/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Cpu.c
**     Project     : QPExMainDeffine_V7790
**     Processor   : MK70FN1M0VMJ15
**     Component   : MK70FN1M0MJ15
**     Version     : Component 01.028, Driver 01.04, CPU db: 3.00.000
**     Datasheet   : K70P256M150SF3RM, Rev. 2, Dec 2011
**     Compiler    : GNU C Compiler
**     Date/Time   : 2021-04-07, 14:48, # CodeGen: 0
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         SystemReset - void Cpu_SystemReset(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 01.04
** @brief
**
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */

/* {Default RTOS Adapter} No RTOS includes */
#include "HAL_TICKS.h"
#include "HAL_LEDS.h"
#include "HAL_WIFI_RESET_PIO.h"
#include "TX_ENABLE_PIO.h"
#include "HAL_PWM_1.h"
#include "HAL_RTC.h"
#include "HAL_UART_2.h"
#include "HAL_UART_4.h"
#include "HAL_UART_5.h"
#include "Shtdn.h"
#include "tscrSPI.h"
#include "tscrIrq.h"
#include "HAL_SPI_2.h"
#include "HAL_CS_ACCEL.h"
#include "HAL_CS_FLASH.h"
#include "HAL_INTERRUPT_ACCEL.h"
#include "AD1.h"
#include "NFC1.h"
#include "LED_AG.h"
#include "LED_AY.h"
#include "LED_K12.h"
#include "LED_K34.h"
#include "FLASH1.h"
#include "usb_host.h"
#include "USB_LDD.h"
#include "HAL_USB_VBUS_ENA_PIO.h"
#include "Ventilador_PIO.h"
#include "Alarma_PIO.h"
#include "Alarma_Inpt.h"
#include "TimerTouch.h"
#include "TimeBuzzer.h"
#include "HAL_WDog.h"
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Global variables */
volatile uint8_t SR_reg;               /* Current value of the FAULTMASK register */
volatile uint8_t SR_lock = 0x00U;      /* Lock */

/*
** ===================================================================
**     Method      :  Cpu_SetBASEPRI (component MK70FN1M0MJ15)
**
**     Description :
**         This method sets the BASEPRI core register.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void Cpu_SetBASEPRI(uint32_t Level);

/*
** ===================================================================
**     Method      :  Cpu_SystemReset (component MK70FN1M0MJ15)
*/
/*!
**     @brief
**         This method initiates a system reset request to reset the
**         CPU.
*/
/* ===================================================================*/
void Cpu_SystemReset(void)
{
  /* SCB_AIRCR: VECTKEY=0x05FA,SYSRESETREQ=1 */
  SCB_AIRCR = (uint32_t)((SCB_AIRCR & (uint32_t)~(uint32_t)(
               SCB_AIRCR_VECTKEY(0xFA05)
              )) | (uint32_t)(
               SCB_AIRCR_VECTKEY(0x05FA) |
               SCB_AIRCR_SYSRESETREQ_MASK
              ));                      /* Request system reset */
  while(1) {                           /* Wait until reset */
  }
}

/*
** ===================================================================
**     Method      :  Cpu_INT_NMIInterrupt (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services the Non Maskable Interrupt interrupt.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_INT_NMIInterrupt)
{
  Cpu_OnNMIINT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Hard_Fault (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Hard_Fault)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Mem_Manage_Fault (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Mem_Manage_Fault)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Bus_Fault (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Bus_Fault)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Usage_Fault (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Usage_Fault)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved7 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved7)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved8 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved8)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved9 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved9)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved10 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved10)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_SVCall (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_SVCall)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DebugMonitor (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DebugMonitor)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved13 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved13)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PendableSrvReq (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PendableSrvReq)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_SysTick (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_SysTick)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA0_DMA16 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA0_DMA16)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA1_DMA17 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA1_DMA17)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA2_DMA18 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA2_DMA18)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA3_DMA19 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA3_DMA19)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA4_DMA20 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA4_DMA20)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA5_DMA21 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA5_DMA21)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA6_DMA22 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA6_DMA22)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA7_DMA23 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA7_DMA23)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA8_DMA24 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA8_DMA24)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA9_DMA25 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA9_DMA25)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA10_DMA26 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA10_DMA26)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA11_DMA27 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA11_DMA27)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA12_DMA28 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA12_DMA28)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA13_DMA29 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA13_DMA29)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA14_DMA30 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA14_DMA30)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA15_DMA31 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA15_DMA31)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DMA_Error (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DMA_Error)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_MCM (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_MCM)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_FTFE (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_FTFE)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Read_Collision (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Read_Collision)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_LVD_LVW (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_LVD_LVW)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_LLW (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_LLW)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Watchdog (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Watchdog)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_RNG (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_RNG)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_I2C0 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_I2C0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_I2C1 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_I2C1)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_SPI1 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_SPI1)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN0_ORed_Message_buffer (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN0_ORed_Message_buffer)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN0_Bus_Off (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN0_Bus_Off)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN0_Error (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN0_Error)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN0_Tx_Warning (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN0_Tx_Warning)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN0_Rx_Warning (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN0_Rx_Warning)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN0_Wake_Up (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN0_Wake_Up)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_I2S0_Tx (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_I2S0_Tx)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_I2S0_Rx (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_I2S0_Rx)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN1_ORed_Message_buffer (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN1_ORed_Message_buffer)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN1_Bus_Off (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN1_Bus_Off)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN1_Error (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN1_Error)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN1_Tx_Warning (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN1_Tx_Warning)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN1_Rx_Warning (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN1_Rx_Warning)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CAN1_Wake_Up (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CAN1_Wake_Up)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved59 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved59)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_UART0_LON (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_UART0_LON)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_UART0_RX_TX (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_UART0_RX_TX)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_UART0_ERR (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_UART0_ERR)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_UART1_RX_TX (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_UART1_RX_TX)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_UART1_ERR (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_UART1_ERR)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_UART3_RX_TX (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_UART3_RX_TX)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_UART3_ERR (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_UART3_ERR)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_ADC1 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_ADC1)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CMP0 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CMP0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CMP1 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CMP1)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CMP2 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CMP2)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_FTM1 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_FTM1)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CMT (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CMT)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_RTC_Seconds (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_RTC_Seconds)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PIT0 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PIT0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PIT1 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PIT1)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PIT2 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PIT2)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PIT3 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PIT3)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PDB0 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PDB0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_USBDCD (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_USBDCD)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_ENET_1588_Timer (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_ENET_1588_Timer)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_ENET_Transmit (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_ENET_Transmit)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_ENET_Receive (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_ENET_Receive)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_ENET_Error (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_ENET_Error)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved95 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved95)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_SDHC (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_SDHC)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DAC0 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DAC0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DAC1 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DAC1)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_TSI0 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_TSI0)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_MCG (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_MCG)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_LPTimer (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_LPTimer)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved102 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved102)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PORTC (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PORTC)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PORTD (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PORTD)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_PORTF (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_PORTF)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_DDR (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_DDR)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_SWI (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_SWI)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_USBHS (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_USBHS)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_LCD (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_LCD)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_CMP3 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_CMP3)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved115 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved115)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_Reserved116 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_Reserved116)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_ADC2 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_ADC2)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_ADC3 (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_ADC3)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_I2S1_Tx (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_I2S1_Tx)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}

/*
** ===================================================================
**     Method      :  Cpu_Cpu_ivINT_I2S1_Rx (component MK70FN1M0MJ15)
**
**     Description :
**         This ISR services an unused interrupt/exception vector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(Cpu_ivINT_I2S1_Rx)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  Cpu_SystemReset();
  PE_DEBUGHALT();
}


/*** !!! Here you can place your own code using property "User data declarations" on the build options tab. !!! ***/

/*lint -esym(765,__init_hardware) Disable MISRA rule (8.10) checking for symbols (__init_hardware). The function is linked to the EWL library */
/*lint -esym(765,Cpu_Interrupt) Disable MISRA rule (8.10) checking for symbols (Cpu_Interrupt). */
void __init_hardware(void)
{

  /*** !!! Here you can place your own code before PE initialization using property "User code before PE initialization" on the build options tab. !!! ***/

  /*** ### MK70FN1M0VMJ15 "Cpu" init code ... ***/
  /*** PE initialization code after reset ***/
  SCB_VTOR = (uint32_t)(&__vect_table); /* Set the interrupt vector table position */
  /* SIM_SCGC6: RTC=1 */
  SIM_SCGC6 |= SIM_SCGC6_RTC_MASK;
  if ((RTC_CR & RTC_CR_OSCE_MASK) == 0u) { /* Only if the OSCILLATOR is not already enabled */
    /* RTC_CR: SC2P=0,SC4P=0,SC8P=0,SC16P=0 */
    RTC_CR &= (uint32_t)~(uint32_t)(
               RTC_CR_SC2P_MASK |
               RTC_CR_SC4P_MASK |
               RTC_CR_SC8P_MASK |
               RTC_CR_SC16P_MASK
              );
    /* RTC_CR: OSCE=1 */
    RTC_CR |= RTC_CR_OSCE_MASK;
    /* RTC_CR: CLKO=0 */
    RTC_CR &= (uint32_t)~(uint32_t)(RTC_CR_CLKO_MASK);
  }
  /* Disable the WDOG module */
  /* WDOG_UNLOCK: WDOGUNLOCK=0xC520 */
  WDOG_UNLOCK = WDOG_UNLOCK_WDOGUNLOCK(0xC520); /* Key 1 */
  /* WDOG_UNLOCK: WDOGUNLOCK=0xD928 */
  WDOG_UNLOCK = WDOG_UNLOCK_WDOGUNLOCK(0xD928); /* Key 2 */
  /* WDOG_STCTRLH: ??=0,DISTESTWDOG=0,BYTESEL=0,TESTSEL=0,TESTWDOG=0,??=0,??=1,WAITEN=1,STOPEN=1,DBGEN=0,ALLOWUPDATE=1,WINEN=0,IRQRSTEN=0,CLKSRC=1,WDOGEN=0 */
  WDOG_STCTRLH = WDOG_STCTRLH_BYTESEL(0x00) |
                 WDOG_STCTRLH_WAITEN_MASK |
                 WDOG_STCTRLH_STOPEN_MASK |
                 WDOG_STCTRLH_ALLOWUPDATE_MASK |
                 WDOG_STCTRLH_CLKSRC_MASK |
                 0x0100U;

  /* System clock initialization */
  /* SIM_CLKDIV1: OUTDIV1=0,OUTDIV2=1,OUTDIV3=3,OUTDIV4=3,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  SIM_CLKDIV1 = SIM_CLKDIV1_OUTDIV1(0x00) |
                SIM_CLKDIV1_OUTDIV2(0x01) |
                SIM_CLKDIV1_OUTDIV3(0x03) |
                SIM_CLKDIV1_OUTDIV4(0x03); /* Set the system prescalers to safe value */
  /* SIM_SCGC5: PORTF=1,PORTE=1,PORTD=1,PORTC=1,PORTB=1,PORTA=1 */
  SIM_SCGC5 |= SIM_SCGC5_PORTF_MASK |
               SIM_SCGC5_PORTE_MASK |
               SIM_SCGC5_PORTD_MASK |
               SIM_SCGC5_PORTC_MASK |
               SIM_SCGC5_PORTB_MASK |
               SIM_SCGC5_PORTA_MASK;   /* Enable clock gate for ports to enable pin routing */
  if ((PMC_REGSC & PMC_REGSC_ACKISO_MASK) != 0x0U) {
    /* PMC_REGSC: ACKISO=1 */
    PMC_REGSC |= PMC_REGSC_ACKISO_MASK; /* Release IO pads after wakeup from VLLS mode. */
  }
  /* SIM_CLKDIV1: OUTDIV1=0,OUTDIV2=1,OUTDIV3=1,OUTDIV4=5,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  SIM_CLKDIV1 = SIM_CLKDIV1_OUTDIV1(0x00) |
                SIM_CLKDIV1_OUTDIV2(0x01) |
                SIM_CLKDIV1_OUTDIV3(0x01) |
                SIM_CLKDIV1_OUTDIV4(0x05); /* Update system prescalers */
  /* SIM_SOPT2: PLLFLLSEL=0 */
  SIM_SOPT2 &= (uint32_t)~(uint32_t)(SIM_SOPT2_PLLFLLSEL(0x03)); /* Select FLL as a clock source for various peripherals */
  /* SIM_SOPT1: OSC32KSEL=0 */
  SIM_SOPT1 &= (uint32_t)~(uint32_t)(SIM_SOPT1_OSC32KSEL_MASK); /* System oscillator drives 32 kHz clock for various peripherals */
  /* SIM_SCGC1: OSC1=1 */
  SIM_SCGC1 |= SIM_SCGC1_OSC1_MASK;
  /* PORTA_PCR18: ISF=0,MUX=0 */
  PORTA_PCR18 &= (uint32_t)~(uint32_t)((PORT_PCR_ISF_MASK | PORT_PCR_MUX(0x07)));
  /* Switch to FBE Mode */
  /* MCG_C7: OSCSEL=0 */
  MCG_C7 &= (uint8_t)~(uint8_t)(MCG_C7_OSCSEL_MASK);
  /* MCG_C10: LOCRE2=0,??=0,RANGE1=0,HGO1=0,EREFS1=0,??=0,??=0 */
  MCG_C10 = MCG_C10_RANGE1(0x00);
  /* MCG_C2: LOCRE0=0,??=0,RANGE0=2,HGO0=0,EREFS0=0,LP=0,IRCS=0 */
  MCG_C2 = MCG_C2_RANGE0(0x02);
  /* OSC0_CR: ERCLKEN=1,??=0,EREFSTEN=0,??=0,SC2P=0,SC4P=0,SC8P=0,SC16P=0 */
  OSC0_CR = OSC_CR_ERCLKEN_MASK;
  /* OSC1_CR: ERCLKEN=1,??=0,EREFSTEN=0,??=0,SC2P=0,SC4P=0,SC8P=0,SC16P=0 */
  OSC1_CR = OSC_CR_ERCLKEN_MASK;
  /* MCG_C1: CLKS=2,FRDIV=5,IREFS=0,IRCLKEN=1,IREFSTEN=0 */
  MCG_C1 = (MCG_C1_CLKS(0x02) | MCG_C1_FRDIV(0x05) | MCG_C1_IRCLKEN_MASK);
  /* MCG_C4: DMX32=0,DRST_DRS=0 */
  MCG_C4 &= (uint8_t)~(uint8_t)((MCG_C4_DMX32_MASK | MCG_C4_DRST_DRS(0x03)));
  /* MCG_C5: PLLREFSEL0=0,PLLCLKEN0=0,PLLSTEN0=0,??=0,??=0,PRDIV0=4 */
  MCG_C5 = MCG_C5_PRDIV0(0x04);
  /* MCG_C6: LOLIE0=0,PLLS=0,CME0=0,VDIV0=8 */
  MCG_C6 = MCG_C6_VDIV0(0x08);
  /* MCG_C11: PLLREFSEL1=0,PLLCLKEN1=0,PLLSTEN1=0,PLLCS=0,??=0,PRDIV1=4 */
  MCG_C11 = MCG_C11_PRDIV1(0x04);
  /* MCG_C11: PLLCLKEN1=1 */
  MCG_C11 |= MCG_C11_PLLCLKEN1_MASK;   /* Enable the PLL */
  /* MCG_C12: LOLIE1=0,??=0,CME2=0,VDIV1=8 */
  MCG_C12 = MCG_C12_VDIV1(0x08);
  while((MCG_S & MCG_S_IREFST_MASK) != 0x00U) { /* Check that the source of the FLL reference clock is the external reference clock. */
  }
  while((MCG_S & 0x0CU) != 0x08U) {    /* Wait until external reference clock is selected as MCG output */
  }
  /* Switch to PBE Mode */
  /* MCG_C6: LOLIE0=0,PLLS=1,CME0=0,VDIV0=8 */
  MCG_C6 = (MCG_C6_PLLS_MASK | MCG_C6_VDIV0(0x08));
  while((MCG_S & 0x0CU) != 0x08U) {    /* Wait until external reference clock is selected as MCG output */
  }
  while((MCG_S & MCG_S_LOCK0_MASK) == 0x00U) { /* Wait until PLL locked */
  }
  /* Switch to PEE Mode */
  /* MCG_C1: CLKS=0,FRDIV=5,IREFS=0,IRCLKEN=1,IREFSTEN=0 */
  MCG_C1 = (MCG_C1_CLKS(0x00) | MCG_C1_FRDIV(0x05) | MCG_C1_IRCLKEN_MASK);
  while((MCG_S & 0x0CU) != 0x0CU) {    /* Wait until output of the PLL is selected */
  }
        /* Initialization of the DDR module */
  /* SIM_SCGC3: DDR=1 */
  SIM_SCGC3 |= SIM_SCGC3_DDR_MASK;
  /* MCM_CR: DDRSIZE=1 */
  MCM_CR = (uint32_t)((MCM_CR & (uint32_t)~(uint32_t)(
            MCM_CR_DDRSIZE(0x02)
           )) | (uint32_t)(
            MCM_CR_DDRSIZE(0x01)
           ));
  /* SIM_MCR: DDRCFG=6,??=0,DDRPEN=1,DDRSREN=0 */
  SIM_MCR = (uint32_t)((SIM_MCR & (uint32_t)~(uint32_t)(
             SIM_MCR_DDRCFG(0x01) |
             SIM_MCR_DDRSREN_MASK |
             0x10U
            )) | (uint32_t)(
             SIM_MCR_DDRCFG(0x06) |
             SIM_MCR_DDRPEN_MASK
            ));
  /* DDR_RCR: RST=1 */
  DDR_RCR |= DDR_RCR_RST_MASK;
  /* DDR_CR00: DDRCLS=4 */
  DDR_CR00 = (uint32_t)((DDR_CR00 & (uint32_t)~(uint32_t)(
              DDR_CR00_DDRCLS(0x0B)
             )) | (uint32_t)(
              DDR_CR00_DDRCLS(0x04)
             ));
  /* DDR_CR02: INITAREF=2,TINIT=0x31 */
  DDR_CR02 = (uint32_t)((DDR_CR02 & (uint32_t)~(uint32_t)(
              DDR_CR02_INITAREF(0x0D) |
              DDR_CR02_TINIT(0x00FFFFCE)
             )) | (uint32_t)(
              DDR_CR02_INITAREF(0x02) |
              DDR_CR02_TINIT(0x31)
             ));
  /* DDR_CR03: TCCD=2,WRLAT=2,LATGATE=5,LATLIN=6 */
  DDR_CR03 = (uint32_t)((DDR_CR03 & (uint32_t)~(uint32_t)(
              DDR_CR03_TCCD(0x1D) |
              DDR_CR03_WRLAT(0x0D) |
              DDR_CR03_LATGATE(0x0A) |
              DDR_CR03_LATLIN(0x09)
             )) | (uint32_t)(
              DDR_CR03_TCCD(0x02) |
              DDR_CR03_WRLAT(0x02) |
              DDR_CR03_LATGATE(0x05) |
              DDR_CR03_LATLIN(0x06)
             ));
  /* DDR_CR04: TRASMIN=6,TRC=9,TRRD=2,TBINT=2 */
  DDR_CR04 = (uint32_t)((DDR_CR04 & (uint32_t)~(uint32_t)(
              DDR_CR04_TRASMIN(0xF9) |
              DDR_CR04_TRC(0x36) |
              DDR_CR04_TRRD(0x05) |
              DDR_CR04_TBINT(0x05)
             )) | (uint32_t)(
              DDR_CR04_TRASMIN(0x06) |
              DDR_CR04_TRC(0x09) |
              DDR_CR04_TRRD(0x02) |
              DDR_CR04_TBINT(0x02)
             ));
  /* DDR_CR05: TMRD=2,TRTP=2,TRP=3,TWTR=2 */
  DDR_CR05 = (uint32_t)((DDR_CR05 & (uint32_t)~(uint32_t)(
              DDR_CR05_TMRD(0x1D) |
              DDR_CR05_TRTP(0x05) |
              DDR_CR05_TRP(0x0C) |
              DDR_CR05_TWTR(0x0D)
             )) | (uint32_t)(
              DDR_CR05_TMRD(0x02) |
              DDR_CR05_TRTP(0x02) |
              DDR_CR05_TRP(0x03) |
              DDR_CR05_TWTR(0x02)
             ));
  /* DDR_CR06: INTWBR=0,TRASMAX=0x9040,TMOD=2 */
  DDR_CR06 = (uint32_t)((DDR_CR06 & (uint32_t)~(uint32_t)(
              DDR_CR06_INTWBR_MASK |
              DDR_CR06_TRASMAX(0x6FBF) |
              DDR_CR06_TMOD(0xFD)
             )) | (uint32_t)(
              DDR_CR06_TRASMAX(0x9040) |
              DDR_CR06_TMOD(0x02)
             ));
  /* DDR_CR07: AP=0,TCKESR=3,CLKPW=3 */
  DDR_CR07 = (uint32_t)((DDR_CR07 & (uint32_t)~(uint32_t)(
              DDR_CR07_AP_MASK |
              DDR_CR07_TCKESR(0x1C) |
              DDR_CR07_CLKPW(0x04)
             )) | (uint32_t)(
              DDR_CR07_TCKESR(0x03) |
              DDR_CR07_CLKPW(0x03)
             ));
  /* DDR_CR08: TDAL=5,TWR=3,TRASDI=2,TRAS=1 */
  DDR_CR08 = (uint32_t)((DDR_CR08 & (uint32_t)~(uint32_t)(
              DDR_CR08_TDAL(0x1A) |
              DDR_CR08_TWR(0x1C) |
              DDR_CR08_TRASDI(0xFD)
             )) | (uint32_t)(
              DDR_CR08_TDAL(0x05) |
              DDR_CR08_TWR(0x03) |
              DDR_CR08_TRASDI(0x02) |
              DDR_CR08_TRAS_MASK
             ));
  /* DDR_CR09: BSTLEN=2,NOCMD=0,TDLL=0xC8 */
  DDR_CR09 = (uint32_t)((DDR_CR09 & (uint32_t)~(uint32_t)(
              DDR_CR09_BSTLEN(0x05) |
              DDR_CR09_NOCMD_MASK |
              DDR_CR09_TDLL(0xFF37)
             )) | (uint32_t)(
              DDR_CR09_BSTLEN(0x02) |
              DDR_CR09_TDLL(0xC8)
             ));
  /* DDR_CR10: TRPAB=3,TCPD=0x32,TFAW=7 */
  DDR_CR10 = (uint32_t)((DDR_CR10 & (uint32_t)~(uint32_t)(
              DDR_CR10_TRPAB(0x0C) |
              DDR_CR10_TCPD(0xFFCD) |
              DDR_CR10_TFAW(0x38)
             )) | (uint32_t)(
              DDR_CR10_TRPAB(0x03) |
              DDR_CR10_TCPD(0x32) |
              DDR_CR10_TFAW(0x07)
             ));
  /* DDR_CR11: TREFEN=1,AREFMODE=0,REGDIMM=0 */
  DDR_CR11 = (uint32_t)((DDR_CR11 & (uint32_t)~(uint32_t)(
              DDR_CR11_AREFMODE_MASK |
              DDR_CR11_REGDIMM_MASK
             )) | (uint32_t)(
              DDR_CR11_TREFEN_MASK
             ));
  /* DDR_CR12: TREF=0x0492,TRFC=0x31 */
  DDR_CR12 = (uint32_t)((DDR_CR12 & (uint32_t)~(uint32_t)(
              DDR_CR12_TREF(0x3B6D) |
              DDR_CR12_TRFC(0x03CE)
             )) | (uint32_t)(
              DDR_CR12_TREF(0x0492) |
              DDR_CR12_TRFC(0x31)
             ));
  /* DDR_CR13: PD=0 */
  DDR_CR13 &= (uint32_t)~(uint32_t)(DDR_CR13_PD_MASK);
  /* DDR_CR15: PUREF=0,SREF=0,TXSNR=0x32 */
  DDR_CR15 = (uint32_t)((DDR_CR15 & (uint32_t)~(uint32_t)(
              DDR_CR15_PUREF_MASK |
              DDR_CR15_SREF_MASK |
              DDR_CR15_TXSNR(0xFFCD)
             )) | (uint32_t)(
              DDR_CR15_TXSNR(0x32)
             ));
  /* DDR_CR16: LPCTRL=0,CLKDLY=0,QKREF=0 */
  DDR_CR16 &= (uint32_t)~(uint32_t)(
               DDR_CR16_LPCTRL(0x1F) |
               DDR_CR16_CLKDLY(0x07) |
               DDR_CR16_QKREF_MASK
              );
  /* DDR_CR17: LPRFCNT=0,LPPDCNT=0 */
  DDR_CR17 = (DDR_CR17_LPRFCNT(0x00) | DDR_CR17_LPPDCNT(0x00));
  /* DDR_CR18: LPAUTO=0,LPEXTCNT=0 */
  DDR_CR18 &= (uint32_t)~(uint32_t)(
               DDR_CR18_LPAUTO(0x1F) |
               DDR_CR18_LPEXTCNT(0xFFFF)
              );
  /* DDR_CR19: LPRFHOLD=0,LPINTCNT=0 */
  DDR_CR19 = (DDR_CR19_LPRFHOLD(0x00) | DDR_CR19_LPINTCNT(0x00));
  /* DDR_CR20: CKSRX=3,CKSRE=3,LPRE=0 */
  DDR_CR20 = (uint32_t)((DDR_CR20 & (uint32_t)~(uint32_t)(
              DDR_CR20_CKSRX(0x0C) |
              DDR_CR20_CKSRE(0x0C) |
              DDR_CR20_LPRE(0x03)
             )) | (uint32_t)(
              DDR_CR20_CKSRX(0x03) |
              DDR_CR20_CKSRE(0x03)
             ));
  /* DDR_CR21: MR1DAT0=4,MR0DAT0=0x0232 */
  DDR_CR21 = (DDR_CR21_MR1DAT0(0x04) | DDR_CR21_MR0DAT0(0x0232));
  /* DDR_CR22: MR3DAT0=0,MR2DATA0=0 */
  DDR_CR22 = (DDR_CR22_MR3DAT0(0x00) | DDR_CR22_MR2DATA0(0x00));
  /* DDR_CR25: APREBIT=0x0A,COLSIZ=1,ADDPINS=3,BNK8=1 */
  DDR_CR25 = (uint32_t)((DDR_CR25 & (uint32_t)~(uint32_t)(
              DDR_CR25_APREBIT(0x05) |
              DDR_CR25_COLSIZ(0x06) |
              DDR_CR25_ADDPINS(0x04)
             )) | (uint32_t)(
              DDR_CR25_APREBIT(0x0A) |
              DDR_CR25_COLSIZ(0x01) |
              DDR_CR25_ADDPINS(0x03) |
              DDR_CR25_BNK8_MASK
             ));
  /* DDR_CR26: BNKSPT=1,ADDCOL=1,CMDAGE=0xFF,AGECNT=0xFF */
  DDR_CR26 |= DDR_CR26_BNKSPT_MASK |
              DDR_CR26_ADDCOL_MASK |
              DDR_CR26_CMDAGE(0xFF) |
              DDR_CR26_AGECNT(0xFF);
  /* DDR_CR27: SWPEN=1,RWEN=1,PRIEN=1,PLEN=1 */
  DDR_CR27 |= DDR_CR27_SWPEN_MASK |
              DDR_CR27_RWEN_MASK |
              DDR_CR27_PRIEN_MASK |
              DDR_CR27_PLEN_MASK;
  /* DDR_CR28: CMDLATR=0,BIGEND=0,REDUC=0,CSMAP=1 */
  DDR_CR28 = (uint32_t)((DDR_CR28 & (uint32_t)~(uint32_t)(
              DDR_CR28_CMDLATR_MASK |
              DDR_CR28_BIGEND_MASK |
              DDR_CR28_REDUC_MASK
             )) | (uint32_t)(
              DDR_CR28_CSMAP_MASK
             ));
  /* DDR_CR29: QFULL=0,FSTWR=0,WRLATR=0 */
  DDR_CR29 &= (uint32_t)~(uint32_t)(
               DDR_CR29_QFULL(0x03) |
               DDR_CR29_FSTWR_MASK |
               DDR_CR29_WRLATR_MASK
              );
  /* DDR_CR30: INTACK=0xFF,RSYNCRF=1 */
  DDR_CR30 |= (DDR_CR30_INTACK(0xFF) | DDR_CR30_RSYNCRF_MASK);
  /* DDR_CR31: INTMASK=0 */
  DDR_CR31 &= (uint32_t)~(uint32_t)(DDR_CR31_INTMASK(0x01FF));
  /* DDR_CR34: ODTWRCS=1,ODTRDC=1 */
  DDR_CR34 |= (DDR_CR34_ODTWRCS_MASK | DDR_CR34_ODTRDC_MASK);
  /* DDR_CR37: W2WSAME=0,W2RSAME=0,R2WSAME=2,R2RSAME=0 */
  DDR_CR37 = (uint32_t)((DDR_CR37 & (uint32_t)~(uint32_t)(
              DDR_CR37_W2WSAME(0x07) |
              DDR_CR37_W2RSAME(0x07) |
              DDR_CR37_R2WSAME(0x05) |
              DDR_CR37_R2RSAME(0x07)
             )) | (uint32_t)(
              DDR_CR37_R2WSAME(0x02)
             ));
  /* DDR_CR38: PWRCNT=0x20,PUPCS=0,PDNCS=0 */
  DDR_CR38 = (uint32_t)((DDR_CR38 & (uint32_t)~(uint32_t)(
              DDR_CR38_PWRCNT(0x07DF) |
              DDR_CR38_PUPCS(0x1F) |
              DDR_CR38_PDNCS(0x1F)
             )) | (uint32_t)(
              DDR_CR38_PWRCNT(0x20)
             ));
  /* DDR_CR39: WP0=1,RP0=1,P0RDCNT=0x20 */
  DDR_CR39 = (uint32_t)((DDR_CR39 & (uint32_t)~(uint32_t)(
              DDR_CR39_WP0(0x02) |
              DDR_CR39_RP0(0x02) |
              DDR_CR39_P0RDCNT(0x07DF)
             )) | (uint32_t)(
              DDR_CR39_WP0(0x01) |
              DDR_CR39_RP0(0x01) |
              DDR_CR39_P0RDCNT(0x20)
             ));
  /* DDR_CR40: P1WRCNT=0x20,P0TYP=0 */
  DDR_CR40 = (uint32_t)((DDR_CR40 & (uint32_t)~(uint32_t)(
              DDR_CR40_P1WRCNT(0x07DF) |
              DDR_CR40_P0TYP(0x03)
             )) | (uint32_t)(
              DDR_CR40_P1WRCNT(0x20)
             ));
  /* DDR_CR41: WP1=1,RP1=1,P1RDCNT=0x20 */
  DDR_CR41 = (uint32_t)((DDR_CR41 & (uint32_t)~(uint32_t)(
              DDR_CR41_WP1(0x02) |
              DDR_CR41_RP1(0x02) |
              DDR_CR41_P1RDCNT(0x07DF)
             )) | (uint32_t)(
              DDR_CR41_WP1(0x01) |
              DDR_CR41_RP1(0x01) |
              DDR_CR41_P1RDCNT(0x20)
             ));
  /* DDR_CR42: P2WRCNT=0x20,P1TYP=0 */
  DDR_CR42 = (uint32_t)((DDR_CR42 & (uint32_t)~(uint32_t)(
              DDR_CR42_P2WRCNT(0x07DF) |
              DDR_CR42_P1TYP(0x03)
             )) | (uint32_t)(
              DDR_CR42_P2WRCNT(0x20)
             ));
  /* DDR_CR43: WP2=1,RP2=1,P2RDCNT=0x20 */
  DDR_CR43 = (uint32_t)((DDR_CR43 & (uint32_t)~(uint32_t)(
              DDR_CR43_WP2(0x02) |
              DDR_CR43_RP2(0x02) |
              DDR_CR43_P2RDCNT(0x07DF)
             )) | (uint32_t)(
              DDR_CR43_WP2(0x01) |
              DDR_CR43_RP2(0x01) |
              DDR_CR43_P2RDCNT(0x20)
             ));
  /* DDR_CR44: WRRSHARE=0,WRRLAT=0,P2TYP=0 */
  DDR_CR44 &= (uint32_t)~(uint32_t)(
               DDR_CR44_WRRSHARE_MASK |
               DDR_CR44_WRRLAT_MASK |
               DDR_CR44_P2TYP(0x03)
              );
  /* DDR_CR45: P0PRI3=3,P0PRI2=3,P0PRI1=3,P0PRI0=3 */
  DDR_CR45 = (uint32_t)((DDR_CR45 & (uint32_t)~(uint32_t)(
              DDR_CR45_P0PRI3(0x0C) |
              DDR_CR45_P0PRI2(0x0C) |
              DDR_CR45_P0PRI1(0x0C) |
              DDR_CR45_P0PRI0(0x0C)
             )) | (uint32_t)(
              DDR_CR45_P0PRI3(0x03) |
              DDR_CR45_P0PRI2(0x03) |
              DDR_CR45_P0PRI1(0x03) |
              DDR_CR45_P0PRI0(0x03)
             ));
  /* DDR_CR46: P1PRI0=2,P0PRIRLX=0x64,P0ORD=1 */
  DDR_CR46 = (uint32_t)((DDR_CR46 & (uint32_t)~(uint32_t)(
              DDR_CR46_P1PRI0(0x0D) |
              DDR_CR46_P0PRIRLX(0x039B) |
              DDR_CR46_P0ORD(0x02)
             )) | (uint32_t)(
              DDR_CR46_P1PRI0(0x02) |
              DDR_CR46_P0PRIRLX(0x64) |
              DDR_CR46_P0ORD(0x01)
             ));
  /* DDR_CR47: P1ORD=1,P1PRI3=2,P1PRI2=2,P1PRI1=2 */
  DDR_CR47 = (uint32_t)((DDR_CR47 & (uint32_t)~(uint32_t)(
              DDR_CR47_P1ORD(0x02) |
              DDR_CR47_P1PRI3(0x0D) |
              DDR_CR47_P1PRI2(0x0D) |
              DDR_CR47_P1PRI1(0x0D)
             )) | (uint32_t)(
              DDR_CR47_P1ORD(0x01) |
              DDR_CR47_P1PRI3(0x02) |
              DDR_CR47_P1PRI2(0x02) |
              DDR_CR47_P1PRI1(0x02)
             ));
  /* DDR_CR48: P2PRI1=1,P2PRI0=1,P1PRIRLX=0x64 */
  DDR_CR48 = (uint32_t)((DDR_CR48 & (uint32_t)~(uint32_t)(
              DDR_CR48_P2PRI1(0x0E) |
              DDR_CR48_P2PRI0(0x0E) |
              DDR_CR48_P1PRIRLX(0x039B)
             )) | (uint32_t)(
              DDR_CR48_P2PRI1(0x01) |
              DDR_CR48_P2PRI0(0x01) |
              DDR_CR48_P1PRIRLX(0x64)
             ));
  /* DDR_CR49: P2ORD=2,P2PRI3=1,P2PRI2=1 */
  DDR_CR49 = (uint32_t)((DDR_CR49 & (uint32_t)~(uint32_t)(
              DDR_CR49_P2ORD(0x01) |
              DDR_CR49_P2PRI3(0x0E) |
              DDR_CR49_P2PRI2(0x0E)
             )) | (uint32_t)(
              DDR_CR49_P2ORD(0x02) |
              DDR_CR49_P2PRI3(0x01) |
              DDR_CR49_P2PRI2(0x01)
             ));
  /* DDR_CR50: P2PRIRLX=0x64 */
  DDR_CR50 = (uint32_t)((DDR_CR50 & (uint32_t)~(uint32_t)(
              DDR_CR50_P2PRIRLX(0x039B)
             )) | (uint32_t)(
              DDR_CR50_P2PRIRLX(0x64)
             ));
  /* DDR_CR51: DLLRADLY=0,DLLRSTDLY=0x0400 */
  DDR_CR51 = (uint32_t)((DDR_CR51 & (uint32_t)~(uint32_t)(
              DDR_CR51_DLLRADLY(0xFF) |
              DDR_CR51_DLLRSTDLY(0xFBFF)
             )) | (uint32_t)(
              DDR_CR51_DLLRSTDLY(0x0400)
             ));
  /* DDR_CR52: RDDTENBAS=2,PHYRDLAT=6,PYWRLTBS=2 */
  DDR_CR52 = (uint32_t)((DDR_CR52 & (uint32_t)~(uint32_t)(
              DDR_CR52_RDDTENBAS(0x0D) |
              DDR_CR52_PHYRDLAT(0x09) |
              DDR_CR52_PYWRLTBS(0x0D)
             )) | (uint32_t)(
              DDR_CR52_RDDTENBAS(0x02) |
              DDR_CR52_PHYRDLAT(0x06) |
              DDR_CR52_PYWRLTBS(0x02)
             ));
  /* DDR_CR53: CTRLUPDMX=0x03C8,CLKDISCS=0 */
  DDR_CR53 = (uint32_t)((DDR_CR53 & (uint32_t)~(uint32_t)(
              DDR_CR53_CTRLUPDMX(0x3C37) |
              DDR_CR53_CLKDISCS_MASK
             )) | (uint32_t)(
              DDR_CR53_CTRLUPDMX(0x03C8)
             ));
  /* DDR_CR54: PHYUPDTY1=0x03C8,PHYUPDTY0=0x03C8 */
  DDR_CR54 = (uint32_t)((DDR_CR54 & (uint32_t)~(uint32_t)(
              DDR_CR54_PHYUPDTY1(0x3C37) |
              DDR_CR54_PHYUPDTY0(0x3C37)
             )) | (uint32_t)(
              DDR_CR54_PHYUPDTY1(0x03C8) |
              DDR_CR54_PHYUPDTY0(0x03C8)
             ));
  /* DDR_CR55: PHYUPDTY3=0x03C8,PHYUPDTY2=0x03C8 */
  DDR_CR55 = (uint32_t)((DDR_CR55 & (uint32_t)~(uint32_t)(
              DDR_CR55_PHYUPDTY3(0x3C37) |
              DDR_CR55_PHYUPDTY2(0x3C37)
             )) | (uint32_t)(
              DDR_CR55_PHYUPDTY3(0x03C8) |
              DDR_CR55_PHYUPDTY2(0x03C8)
             ));
  /* DDR_CR56: WRLATADJ=2,RDLATADJ=3,PHYUPDRESP=0x03C8 */
  DDR_CR56 = (uint32_t)((DDR_CR56 & (uint32_t)~(uint32_t)(
              DDR_CR56_WRLATADJ(0x0D) |
              DDR_CR56_RDLATADJ(0x0C) |
              DDR_CR56_PHYUPDRESP(0x3C37)
             )) | (uint32_t)(
              DDR_CR56_WRLATADJ(0x02) |
              DDR_CR56_RDLATADJ(0x03) |
              DDR_CR56_PHYUPDRESP(0x03C8)
             ));
  /* DDR_CR57: ODTALTEN=1,CLKENDLY=1,CLKDISDLY=0,CMDDLY=2 */
  DDR_CR57 = (uint32_t)((DDR_CR57 & (uint32_t)~(uint32_t)(
              DDR_CR57_CLKENDLY(0x0E) |
              DDR_CR57_CLKDISDLY(0x07) |
              DDR_CR57_CMDDLY(0x0D)
             )) | (uint32_t)(
              DDR_CR57_ODTALTEN_MASK |
              DDR_CR57_CLKENDLY(0x01) |
              DDR_CR57_CMDDLY(0x02)
             ));
  /* DDR_PAD_CTRL: PAD_ODT_CS0=0,SPARE_DLY_CTRL=0 */
  DDR_PAD_CTRL &= (uint32_t)~(uint32_t)(
                   DDR_PAD_CTRL_PAD_ODT_CS0(0x03) |
                   DDR_PAD_CTRL_SPARE_DLY_CTRL(0x0F)
                  );
  /* DDR_CR00: START=1 */
  DDR_CR00 |= DDR_CR00_START_MASK;
  while ((DDR_CR30 & DDR_CR30_INTSTAT(0x4U)) != DDR_CR30_INTSTAT(0x4U)) {}
  /* Common initialization in Entrypoint */
  /* NVICIP93: PRI93=0 */
  NVICIP93 = NVIC_IP_PRI93(0x00);
  /*** End of PE initialization code after reset ***/

  /*** !!! Here you can place your own code after PE initialization using property "User code after PE initialization" on the build options tab. !!! ***/

}

/*
** ===================================================================
**     Method      :  Cpu_SetBASEPRI (component MK70FN1M0MJ15)
**
**     Description :
**         This method sets the BASEPRI core register.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/*lint -save  -e586 -e950 Disable MISRA rule (2.1,1.1) checking. */
#ifdef _lint
  #define Cpu_SetBASEPRI(Level)  /* empty */
#else
void Cpu_SetBASEPRI(uint32_t Level) {
  __asm ("msr basepri, %[input]"::[input] "r" (Level):);
}
#endif
/*lint -restore Enable MISRA rule (2.1,1.1) checking. */


/*
** ===================================================================
**     Method      :  PE_low_level_init (component MK70FN1M0MJ15)
**
**     Description :
**         Initializes beans and provides common register initialization. 
**         The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  #ifdef PEX_RTOS_INIT
    PEX_RTOS_INIT();                   /* Initialization of the selected RTOS. Macro is defined by the RTOS component. */
  #endif
      /* Initialization of the SIM module */
  /* SIM_SOPT2: CMTUARTPAD=0 */
  SIM_SOPT2 &= (uint32_t)~(uint32_t)(SIM_SOPT2_CMTUARTPAD_MASK);
  /* PORTA_PCR4: ISF=0,MUX=7 */
  PORTA_PCR4 = (uint32_t)((PORTA_PCR4 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x07)
               ));
        /* Initialization of the RCM module */
  /* RCM_RPFW: RSTFLTSEL=0 */
  RCM_RPFW &= (uint8_t)~(uint8_t)(RCM_RPFW_RSTFLTSEL(0x1F));
  /* RCM_RPFC: RSTFLTSS=0,RSTFLTSRW=0 */
  RCM_RPFC &= (uint8_t)~(uint8_t)(
               RCM_RPFC_RSTFLTSS_MASK |
               RCM_RPFC_RSTFLTSRW(0x03)
              );
        /* Initialization of the FTFL_FlashConfig module */
  /* SIM_SCGC7: MPU=1 */
  SIM_SCGC7 |= SIM_SCGC7_MPU_MASK;
        /* Initialization of the MPU module */
  /* MPU_CESR: SPERR=0,VLD=0 */
  MPU_CESR &= (uint32_t)~(uint32_t)((MPU_CESR_SPERR(0xFF) | MPU_CESR_VLD_MASK));
      /* Initialization of the PMC module */
  /* PMC_REGSC: ACKISO=0,BGBE=0 */
  PMC_REGSC &= (uint8_t)~(uint8_t)(
                PMC_REGSC_ACKISO_MASK |
                PMC_REGSC_BGBE_MASK
               );
  /* PMC_LVDSC1: LVDACK=1,LVDIE=0,LVDRE=1,LVDV=0 */
  PMC_LVDSC1 = (uint8_t)((PMC_LVDSC1 & (uint8_t)~(uint8_t)(
                PMC_LVDSC1_LVDIE_MASK |
                PMC_LVDSC1_LVDV(0x03)
               )) | (uint8_t)(
                PMC_LVDSC1_LVDACK_MASK |
                PMC_LVDSC1_LVDRE_MASK
               ));
  /* PMC_LVDSC2: LVWACK=1,LVWIE=0,LVWV=0 */
  PMC_LVDSC2 = (uint8_t)((PMC_LVDSC2 & (uint8_t)~(uint8_t)(
                PMC_LVDSC2_LVWIE_MASK |
                PMC_LVDSC2_LVWV(0x03)
               )) | (uint8_t)(
                PMC_LVDSC2_LVWACK_MASK
               ));
  /* SMC_PMPROT: ??=0,??=0,AVLP=0,??=0,ALLS=0,??=0,AVLLS=0,??=0 */
  SMC_PMPROT = 0x00U;                  /* Setup Power mode protection register */
  /* Common initialization of the CPU registers */
  /* NVICIP20: PRI20=0 */
  NVICIP20 = NVIC_IP_PRI20(0x00);
  /* GPIOE_PDDR: PDD&=~4 */
  GPIOE_PDDR &= (uint32_t)~(uint32_t)(GPIO_PDDR_PDD(0x04));
  /* GPIOB_PDDR: PDD&=~0x20 */
  GPIOB_PDDR &= (uint32_t)~(uint32_t)(GPIO_PDDR_PDD(0x20));
  /* GPIOA_PDDR: PDD&=~0x00010000 */
  GPIOA_PDDR &= (uint32_t)~(uint32_t)(GPIO_PDDR_PDD(0x00010000));
  /* Write code here ... */
/* ### USB_HOST_STACK "usb_host" init code ... */
/* Write code here ... */
  /* Enable interrupts of the given priority level */
  Cpu_SetBASEPRI(0U);
}
  /* Flash configuration field */
  __attribute__ ((section (".cfmconfig"))) const uint8_t _cfm[0x10] = {
   /* NV_BACKKEY3: KEY=0xFF */
    0xFFU,
   /* NV_BACKKEY2: KEY=0xFF */
    0xFFU,
   /* NV_BACKKEY1: KEY=0xFF */
    0xFFU,
   /* NV_BACKKEY0: KEY=0xFF */
    0xFFU,
   /* NV_BACKKEY7: KEY=0xFF */
    0xFFU,
   /* NV_BACKKEY6: KEY=0xFF */
    0xFFU,
   /* NV_BACKKEY5: KEY=0xFF */
    0xFFU,
   /* NV_BACKKEY4: KEY=0xFF */
    0xFFU,
   /* NV_FPROT3: PROT=0xFF */
    0xFFU,
   /* NV_FPROT2: PROT=0xFF */
    0xFFU,
   /* NV_FPROT1: PROT=0xFF */
    0xFFU,
   /* NV_FPROT0: PROT=0xFF */
    0xFFU,
   /* NV_FSEC: KEYEN=1,MEEN=3,FSLACC=3,SEC=2 */
    0x7EU,
   /* NV_FOPT: ??=1,??=1,??=1,??=1,??=1,??=1,EZPORT_DIS=1,LPBOOT=1 */
    0xFFU,
   /* NV_FEPROT: EPROT=0xFF */
    0xFFU,
   /* NV_FDPROT: DPROT=0xFF */
    0xFFU
  };

/* END Cpu. */

#ifdef __cplusplus
}  /* extern "C" */
#endif

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
