/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : HAL_WDog.c
**     Project     : QPExMainDeffine_V7790
**     Processor   : MK70FN1M0VMJ15
**     Component   : WatchDog_LDD
**     Version     : Component 01.052, Driver 01.09, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2021-04-07, 14:48, # CodeGen: 0
**     Abstract    :
**          The WatchDog component provides a high level API for unified hardware access
**          across various watchdog timer devices.
**     Settings    :
**          Component name                                 : HAL_WDog
**          Device                                         : WDOG
**          Action                                         : Reset CPU
**          Period                                         : 10 sec
**          Windowed mode                                  : Disabled
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Protected                                    : no
**            Auto initialization                          : no
**          CPU clock/configuration selection              : Ignored
**     Contents    :
**         Init    - LDD_TDeviceData* HAL_WDog_Init(LDD_TUserData *UserDataPtr);
**         Enable  - LDD_TError HAL_WDog_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable - LDD_TError HAL_WDog_Disable(LDD_TDeviceData *DeviceDataPtr);
**         Clear   - LDD_TError HAL_WDog_Clear(LDD_TDeviceData *DeviceDataPtr);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file HAL_WDog.c
** @version 01.09
** @brief
**          The WatchDog component provides a high level API for unified hardware access
**          across various watchdog timer devices.
*/         
/*!
**  @addtogroup HAL_WDog_module HAL_WDog module documentation
**  @{
*/         

/* MODULE HAL_WDog. */

#include "HAL_WDog.h"
/* {Default RTOS Adapter} No RTOS includes */
#include "IO_Map.h"

#ifdef __cplusplus
extern "C" {
#endif 

typedef struct {
  LDD_TUserData *UserDataPtr;          /* RTOS device data structure */
} HAL_WDog_TDeviceData;

typedef HAL_WDog_TDeviceData *HAL_WDog_TDeviceDataPtr; /* Pointer to the device data structure. */

/* {Default RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static HAL_WDog_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC;


/* Internal method prototypes */
/*
** ===================================================================
**     Method      :  HAL_WDog_Init (component WatchDog_LDD)
*/
/*!
**     @brief
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc. If the
**         property <"Enable in init. code"> is set to "yes" value then
**         the device is also enabled (see the description of the
**         <Enable> method). In this case the <Enable> method is not
**         necessary and needn't to be generated. This method can be
**         called only once. Before the second call of Init the <Deinit>
**         must be called first.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* HAL_WDog_Init(LDD_TUserData *UserDataPtr)
{
  /* Allocate device structure */
  HAL_WDog_TDeviceData *DeviceDataPrv;

  /* {Default RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPrv = &DeviceDataPrv__DEFAULT_RTOS_ALLOC;
  DeviceDataPrv->UserDataPtr = UserDataPtr; /* Store the RTOS device structure */
  /* {Default RTOS Adapter} Critical section begin, general PE function is used */
  EnterCritical();
  /* WDOG_UNLOCK: WDOGUNLOCK=0xC520 */
  WDOG_UNLOCK = WDOG_UNLOCK_WDOGUNLOCK(0xC520); /* Key 1 */
  /* WDOG_UNLOCK: WDOGUNLOCK=0xD928 */
  WDOG_UNLOCK = WDOG_UNLOCK_WDOGUNLOCK(0xD928); /* Key 2 */
  /* WDOG_WINH: WINHIGH=0 */
  WDOG_WINH = WDOG_WINH_WINHIGH(0x00); /* Setup window register high */
  /* WDOG_WINL: WINLOW=0 */
  WDOG_WINL = WDOG_WINL_WINLOW(0x00);  /* Setup window register low */
  /* WDOG_TOVALH: TOVALHIGH=0x2400 */
  WDOG_TOVALH = WDOG_TOVALH_TOVALHIGH(0x2400); /* Setup time-out value register high */
  /* WDOG_TOVALL: TOVALLOW=2 */
  WDOG_TOVALL = WDOG_TOVALL_TOVALLOW(0x02); /* Setup time-out value register low */
  /* WDOG_PRESC: ??=0,??=0,??=0,??=0,??=0,PRESCVAL=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  WDOG_PRESC = WDOG_PRESC_PRESCVAL(0x00); /* Setup status register */
  /* WDOG_STCTRLL: INTFLG=1,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=1 */
  WDOG_STCTRLL = (WDOG_STCTRLL_INTFLG_MASK | 0x01U); /* Setup status register */
  /* WDOG_STCTRLH: ??=0,DISTESTWDOG=1,BYTESEL=0,TESTSEL=0,TESTWDOG=0,??=0,??=1,WAITEN=1,STOPEN=1,DBGEN=0,ALLOWUPDATE=1,WINEN=0,IRQRSTEN=0,CLKSRC=1,WDOGEN=1 */
  WDOG_STCTRLH = WDOG_STCTRLH_DISTESTWDOG_MASK |
                 WDOG_STCTRLH_BYTESEL(0x00) |
                 WDOG_STCTRLH_WAITEN_MASK |
                 WDOG_STCTRLH_STOPEN_MASK |
                 WDOG_STCTRLH_ALLOWUPDATE_MASK |
                 WDOG_STCTRLH_CLKSRC_MASK |
                 WDOG_STCTRLH_WDOGEN_MASK |
                 0x0100U;              /* Setup control register */
  /* {Default RTOS Adapter} Critical section end, general PE function is used */
  ExitCritical();
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_HAL_WDog_ID,DeviceDataPrv);
  return ((LDD_TDeviceData *)DeviceDataPrv); /* Return pointer to the device data structure */
}

/*
** ===================================================================
**     Method      :  HAL_WDog_Enable (component WatchDog_LDD)
*/
/*!
**     @brief
**         Enables the watchdog.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
**                           ERR_PROTECT - Device is write protected and
**                           cannot be unlocked.
*/
/* ===================================================================*/
LDD_TError HAL_WDog_Enable(LDD_TDeviceData *DeviceDataPtr)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  if ((WDOG_PDD_GetAllowUpdateStatus(WDOG_BASE_PTR)) != 0U) {
    /* {Default RTOS Adapter} Critical section begin, general PE function is used */
    EnterCritical();
    WDOG_PDD_WriteUnlockReg(WDOG_BASE_PTR, WDOG_PDD_UNLOCK_1);
    WDOG_PDD_WriteUnlockReg(WDOG_BASE_PTR, WDOG_PDD_UNLOCK_2);
    WDOG_PDD_EnableDevice(WDOG_BASE_PTR, PDD_ENABLE);
    /* {Default RTOS Adapter} Critical section end, general PE function is used */
    ExitCritical();
  }
  else {
    return ERR_PROTECT;
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  HAL_WDog_Disable (component WatchDog_LDD)
*/
/*!
**     @brief
**         Disables the watchdog.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
**                           ERR_PROTECT - Device is write protected and
**                           cannot be unlocked.
*/
/* ===================================================================*/
LDD_TError HAL_WDog_Disable(LDD_TDeviceData *DeviceDataPtr)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  if ((WDOG_PDD_GetAllowUpdateStatus(WDOG_BASE_PTR)) != 0U) {
    /* {Default RTOS Adapter} Critical section begin, general PE function is used */
    EnterCritical();
    WDOG_PDD_WriteUnlockReg(WDOG_BASE_PTR, WDOG_PDD_UNLOCK_1);
    WDOG_PDD_WriteUnlockReg(WDOG_BASE_PTR, WDOG_PDD_UNLOCK_2);
    WDOG_PDD_EnableDevice(WDOG_BASE_PTR, PDD_DISABLE);
    /* {Default RTOS Adapter} Critical section end, general PE function is used */
    ExitCritical();
  }
  else {
    return ERR_PROTECT;
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  HAL_WDog_Clear (component WatchDog_LDD)
*/
/*!
**     @brief
**         Clears the watchdog timer (it makes the timer restart from
**         zero).
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
**                           ERR_DISABLED - The component is disabled
*/
/* ===================================================================*/
LDD_TError HAL_WDog_Clear(LDD_TDeviceData *DeviceDataPtr)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  /* Enable test - this test can be disabled by setting the "Ignore enable test"
     property to the "yes" value in the "Configuration inspector" */
  if ((WDOG_PDD_GetEnableDeviceStatus(WDOG_BASE_PTR)) != 0U) {
    /* {Default RTOS Adapter} Critical section begin, general PE function is used */
    EnterCritical();
    WDOG_PDD_WriteRefreshReg(WDOG_BASE_PTR, WDOG_PDD_KEY_1);
    WDOG_PDD_WriteRefreshReg(WDOG_BASE_PTR, WDOG_PDD_KEY_2);
    /* {Default RTOS Adapter} Critical section end, general PE function is used */
    ExitCritical();
  }
  else {
    return ERR_DISABLED;
  }
  return ERR_OK;
}

/* END HAL_WDog. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
