/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : host_shut.h
**     Project   : QPExMainDeffine_V7790
**     Processor : MK70FN1M0MJ15
**     Component : USB_HOST_STACK
**     Version   : Driver 01.00, CPU db: 3.00.000
**     Compiler  : CodeWarrior ARM C Compiler
**     Date/Time : 2021-04-07, 14:48, # CodeGen: 0
**     Abstract  :
**     Settings  :
**     (c) Copyright <company/user-name>, 2011
**     http      : www.<company>.com
**     mail      : info@<company>.com
** ###################################################################*/

#ifndef __host_shut_h__
#define __host_shut_h__

#include "psptypes.h"
#include "host_common.h"
/* List of Function Prototypes */

#ifdef __cplusplus
extern "C" {
#endif

    extern void _usb_host_shutdown (_usb_host_handle);
    extern void _usb_host_bus_control (_usb_host_handle, uint_8);

#ifdef __cplusplus
}
#endif

#endif
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
