/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : host_driver.h
**     Project   : QPExMainDeffine_V7790
**     Processor : MK70FN1M0MJ15
**     Component : USB_HOST_STACK
**     Version   : Driver 01.00, CPU db: 3.00.000
**     Compiler  : CodeWarrior ARM C Compiler
**     Date/Time : 2021-04-07, 14:48, # CodeGen: 0
**     Abstract  :
**     Settings  :
**     (c) Copyright <company/user-name>, 2011
**     http      : www.<company>.com
**     mail      : info@<company>.com
** ###################################################################*/
#ifndef __host_driver_h__
#define __host_driver_h__
#ifdef __cplusplus
extern "C" {
#endif

extern uint_8 _usb_host_driver_install(uint_32,pointer);

#ifdef __cplusplus
}
#endif

#endif
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
